Remove Timeout.timeout from Truemail::Validate::Smtp::Request
truemail-rb/truemail pull request #127
Opened 2021-01-12 11:20 UTC by wikiti

# PR Details

## Description

Remove `Timeout.timeout` from `Truemail::Validate::Smtp::Request`, and replace it with native `Socket` timeout detection the same way it's done on `Truemail::Validate::Smtp::Request`.

## Related Issue

(It's a closed issue, but I propossed a change there that I though it could be usefull).

https://github.com/truemail-rb/truemail/issues/108

## Motivation and Context

Regarding [this article](http://blog.headius.com/2008/02/rubys-threadraise-threadkill-timeoutrb.html) and this [StackOverflow question](https://stackoverflow.com/questions/517219/ruby-see-if-a-port-is-open/38266150#38266150), this change includes the following two benefits:

- Stop using `Timeout.timeout` on a deep class, which may lead on the future to nested timeouts (using `Truemail::Wrapper`), which won't work.
- Use native implementations of timeout detections, which reduces system overhead by avoiding to create and destroy extra threads.

## How Has This Been Tested

Gem has been updated to match the current behaviour. Automatic tests have been updated.

The changes where tested as a monkey patch on a production environment for more than 2 months, using the main `Truemail.validate` function.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the [**CONTRIBUTING** document](https://github.com/truemail-rb/truemail/blob/master/CONTRIBUTING.md)
- [x] I have added tests to cover my changes
- [ x I have run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I have run `rubocop` and `reek` to ensure the code style is valid

2021-01-12 11:50 UTC, bestwebua reviewed
Hi, @wikiti Thanks for your PR! Could you change head branch to [develop](https://github.com/truemail-rb/truemail/blob/master/.github/BRANCH_NAMING_CONVENTION.md). I'll review it deeply tonight.

2021-01-12 11:52 UTC, wikiti commented
@bestwebua Done!

> I'll review it deeply tonight.

Thank you!

2021-01-12 11:56 UTC, bestwebua commented
@wikiti Also, please rebase it with latest develop branch. Here is repo convention: https://github.com/truemail-rb/truemail/blob/master/.github/BRANCH_NAMING_CONVENTION.md

2021-01-12 19:07 UTC, bestwebua requested changes

2021-01-12 19:07 UTC, bestwebua commented on spec/truemail/validate/smtp/request_spec.rb
>      context 'when port opened' do
insert to 9 line: `port_open_status: port_open_status,`
insert to 22 line: `let(:port_open_status)       { proc { true } }`
change '#check_port' block in 42 line:
```ruby
describe '#check_port' do
  let(:response_instance_target_method) { request_instance.check_port }

  context 'when port opened' do
    specify do
      allow(Socket).to receive(:tcp)
        .with(
          mail_server,
          Truemail::Validate::Smtp::Request::SMTP_PORT,
          connect_timeout: connection_timeout
        ) { |&block| expect(block).to eq(port_open_status) }
        .and_return(true)
      expect { request_instance.check_port }
        .to change(response_instance, :port_opened).from(nil).to(true)
    end
  end

  context 'when port closed' do
    let(:error_stubs) do
      allow(Socket).to receive(:tcp)
        .with(
          mail_server,
          Truemail::Validate::Smtp::Request::SMTP_PORT,
          connect_timeout: connection_timeout
        )
        .and_raise(Errno::ETIMEDOUT)
    end

    specify do
      error_stubs
      expect { response_instance_target_method }.to change(response_instance, :port_opened).from(nil).to(false)
    end

    include_examples 'request retry behavior'
  end
end
```

2021-01-12 19:07 UTC, bestwebua commented on spec/truemail/validate/smtp/request_spec.rb
> +        allow(Socket).to receive(:tcp).and_return(true)
For case when we use stubs, you should check all passed params, blocks, etc... Please use code snippet from example above.

2021-01-12 19:24 UTC, bestwebua approved these changes
Awesome! I'll add it into next release shortly. Thanks 🍻

2021-01-12 19:26 UTC, merged

2021-01-13 09:24 UTC, wikiti commented
Thank you @bestwebua !